name: CI

on:
  workflow_dispatch:
    inputs:
      redis_version:
        description: 'Redis version'
        required: true
        default: '6.2.4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build \
            -t twemproxy:test .

      - name: Run test
        run: |
          docker run --rm twemproxy:test --help
