name: CI

on:
  workflow_dispatch:
    inputs:
      redis_version:
        description: 'Redis version'
        required: true
        default: '6.2.4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build \
            --build-arg REDIS_VER=${{ github.event.inputs.redis_version }} \
            -t my-app:${{ github.event.inputs.redis_version }} .

      - name: Build and test in docker
        run: bash ./test_in_docker.sh ${{ github.event.inputs.redis_version }}
